### ISSUE TITLE
When wildcard file in subfolder, "__subfolder\filename__" does not work.

### ISSUE THREAD

**Issue by michikora** [h-a-te/prompt_generator#1]
Currently need to use `__wildcards\subfolder\filename__` to make the script load wildcards in subfolders.
Can this be changed to `__subfolder\filename__`?
That would be easier to use and would be compatible with the tagcomplete script's wildcard auto-completion feature.

Thank you!

**Comment by h-a-te** [comment]
I'm not entirely sure what you mean.

Currently if you do ```__test__``` It will load the file test from the wildcards directory.
if you do ```__nested/test__``` or ```__nested\test__``` it should load test from the wildcards\nested directory.
Is this not the case ?

**Comment by michikora** [comment]
Sorry English is not my native language.
Yes, when I do `__test__` everything is fine.
When I do `__nested/test__` or `__nested\test__` the files in wildcards\nested directory are not loaded.

**Comment by h-a-te** [comment]
Hmm, that is weird. What OS are you running ? I've only been able to run it on windows locally.

**Comment by michikora** [comment]
I was running on windows 10 and tried firefox and chrome, both with the same result.
But if i use `__wildcards\nested\test__`, it can load files in wildcards\nested directory

**Comment by h-a-te** [comment]
Might have fixed the issue with the latest commit, but difficult to know for sure since I could not replicate it locally :(

**Comment by michikora** [comment]
that's weird you can't replicate it, maybe i missed something?
but it works fine now, thank you!
